CREATE TABLE "ADMINISTRADORA".ADMINISTRADORA (
	ID NUMBER(5),
	CONSTRAINT ADMINISTRADORA_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE ADMINISTRADORA.SEQ_ID_ADMINISTRADORA
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
